// Image api function
async function query(userInput) {
    try {
        console.log(userInput);
        console.log("running");
        const data = { "inputs": userInput };

        const response = await fetch(
            "https://xdwvg9no7pefghrn.us-east-1.aws.endpoints.huggingface.cloud",
            {
                headers: {
                    "Accept": "image/png",
                    "Authorization": "Bearer VknySbLLTUjbxXAXCjyfaFIPwUTCeRXbFSOjwRiCxsxFyhbnGjSFalPKrpvvDAaPVzWEevPljilLVDBiTzfIbWFdxOkYJxnOPoHhkkVGzAknaOulWggusSFewzpqsNWM",
                    "Content-Type": "application/json"
                },
                method: "POST",
                body: JSON.stringify(data),
            }
        );

        if (!response.ok) {
            throw new Error(`HTTP error! Status: ${response.status}`);
        }

        const result = await response.blob();
        // console.log(result);
        const imgElement = document.getElementById('marker-img');

        if (imgElement) {
            // console.log(URL.createObjectURL(result));
            imgElement.src = URL.createObjectURL(result);
        } else {
            console.error("Image element not found.");
        }

        console.log('Done');
    } catch (error) {
        console.log('Error:', error);
    }
}

document.getElementById('generateButton').addEventListener('click', () => {
    const value = document.getElementById('userPrompt').value;
    query(value);
});


// Photo annotation config
const markerArea = new markerjs2.MarkerArea(document.getElementById('marker-img'));
markerArea.settings.displayMode = 'popup';
markerArea.renderAtNaturalSize = true;
markerArea.settings.defaultColor = 'black';
markerArea.settings.defaultFillColor = 'white';

markerArea.addEventListener('render', event => {
  document.getElementById('marker-img').src = event.dataUrl;
});

document.getElementById('editButton').addEventListener('click', () => {
    markerArea.show();
});


// function to handle comic panel clicking and selection
let selectedPanel = null;

function handlePanelClick(panel) {
    const isSamePanel = selectedPanel === panel;

    if (selectedPanel) {
        selectedPanel.classList.remove('selected');
    }

    panel.classList.toggle('selected', !isSamePanel);
    selectedPanel = isSamePanel ? null : panel;
}

// Edit image function
function editImage() {
    console.log('Edit button clicked');
}

// Delete image function
function deleteImage() {
    console.log('Delete button clicked');
}

// Change the image of the selected panel to the confirmed image generated by the user
function confirmChanges() {
    const markerImageSrc = document.getElementById('marker-img').src;
    if (selectedPanel) {
        const selectedPanelImage = selectedPanel.querySelector('img');

        if (selectedPanelImage) {
            selectedPanelImage.src = markerImageSrc;
        }
    } else { // If no panel is selected, fill the image in the first empty div(panel)
        const emptyPanels = document.getElementsByClassName("panel-image")
        let i = 0;
        while (emptyPanels[i].src !== "" && i < 10) {
            i++;
        }
        emptyPanels[i].src = markerImageSrc;
    }
}

// Function to download the comic panel
document.getElementById('download-button').addEventListener('click', () => {
    const downloadElement = document.getElementsByClassName("comic-panel-wrapper")[0];
    html2canvas(downloadElement).then(canvas => {
        const dataURL = canvas.toDataURL();
        const a = document.createElement('a');

        a.href = dataURL;
        a.download = 'comic_panel.png';

        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
    });
});